# -*- coding: utf-8 -*-
"""exercise-04-sales-analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AX_Z_liUTMHYJA35MXnlRYykVdM-2U2z

day 2: exercise 4-sales list analysis
"""

# Given data
monthly_sales = [85000, 120000, 95000, 140000, 75000, 160000]

# 1. Sorted list from highest to lowest
sorted_sales = sorted(monthly_sales, reverse=True)
print("Sorted (highest to lowest):", sorted_sales)

# 2. Values above 100000
high_sales = [amount for amount in monthly_sales if amount > 100000]
print("Sales above 100000:", high_sales)

# 3. Each amount with 13% tax added
sales_with_tax = [amount * 1.13 for amount in monthly_sales]
print("Sales with 13% tax:", sales_with_tax)

# 4. Total sales amount
total_sales = sum(monthly_sales)
print("Total sales:", total_sales)

# 5. Average sales amount
average_sales = total_sales / len(monthly_sales)
print("Average sales:", average_sales)