# -*- coding: utf-8 -*-
"""exercise-07-order-summary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/131mZhlBiSoDR0YmPseykqSpD2eBL6fPC

day 2 : exercise 7 - nested order summary
"""

# Given data
orders = {
    "ORD-001": {
        "customer": "Anisha",
        "amount": 2500,
        "status": "Completed"
    },
    "ORD-002": {
        "customer": "Ravi",
        "amount": 1800,
        "status": "Pending"
    },
    "ORD-003": {
        "customer": "Maya",
        "amount": 3200,
        "status": "Completed"
    }
}

# 1. Printing every order ID and customer
print("All orders and customers:")
for order_id, details in orders.items():
    print(f"{order_id}: {details['customer']}")
print()

# 2. Printing only completed orders
print("Completed orders:")
for order_id, details in orders.items():
    if details["status"] == "Completed":
        print(f"{order_id}: {details['customer']} - NPR {details['amount']}")
print()

# 3. Total amount of completed orders
total_completed_amount = sum(
    details["amount"] for details in orders.values() if details["status"] == "Completed"
)
print(f"Total amount of completed orders: NPR {total_completed_amount}")

# 4. Counting pending orders
pending_count = sum(1 for details in orders.values() if details["status"] == "Pending")
print(f"Number of pending orders: {pending_count}")

# 5. Adding a new order
orders["ORD-004"] = {
    "customer": "Sagar",
    "amount": 4100,
    "status": "Pending"
}
print("\nUpdated orders after adding ORD-004:")
for order_id, details in orders.items():
    print(f"{order_id}: {details}")