# -*- coding: utf-8 -*-
"""exercise-06-student-scores.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C5RpsaRDtU96KQYI_BdRPFUXefUBMXkX
"""

# Given data
student_scores = {
    "Anisha": 78,
    "Ravi": 55,
    "Maya": 92,
    "Sagar": 61,
    "Nima": 48
}

# 1. Printing every student and score
print("All students and scores:")
for student, score in student_scores.items():
    print(f"{student}: {score}")
print()

# 2. Dictionary of students who scored at least 60 (dictionary comprehension)
passing_students = {student: score for student, score in student_scores.items() if score >= 60}
print("Passing students (score >= 60):", passing_students)

# 3. Student with the highest score
top_student = max(student_scores, key=student_scores.get)
print(f"Highest scorer: {top_student} with {student_scores[top_student]}")

# 4. Average score
average_score = sum(student_scores.values()) / len(student_scores)
print(f"Average score: {average_score:.2f}")