# -*- coding: utf-8 -*-
"""exercise-03-clean-values.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lTojycOR2uCAclj1xq4Rxhmr1A70cPYz

day 2: exercise 3-clean numeric values
"""

# Given data
raw_values = [100, None, 250, "invalid", 300, None, 450]

# Method 1: Using a loop, continue, and isinstance()
clean_values = []

for value in raw_values:
    if not isinstance(value, int):
        continue
    clean_values.append(value)

print(clean_values)

# Method 2: Using a list comprehension
raw_values = [100, None, 250, "invalid", 300, None, 450]

clean_values = [value for value in raw_values if isinstance(value, int)]

print(clean_values)

