# -*- coding: utf-8 -*-
"""exercise-01-batch-processor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oBOyNzm_wOgiqzKuaYUgoYt_Y84Uqupj

Day 2: exercise 1-batch processor
"""

# Batch Processor
for batch_number in range(1, 11):
    print(f"Processing batch {batch_number}")

    # Checking if it's a multiple of 3
    if batch_number % 3 == 0:
        print("Checkpoint reached")