# -*- coding: utf-8 -*-
"""exercise-02-retry-simulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pg3BlOlwxiiKZESigfg1BTZwC8Wf6RNk

day 2: exercise 2-retry simulation
"""

# Retry Simulation
attempt = 1
max_attempts = 3
operation_successful = False

while attempt <= max_attempts:
    print(f"Attempt {attempt}")

   #simulating success on the second attempt
    if attempt == 2:
        operation_successful = True
        break

    attempt += 1

# Displaying final result after the loop
if operation_successful:
    print("Operation completed successfully")
else:
    print("Operation failed after three attempts")