# -*- coding: utf-8 -*-
"""stretch-contact-book.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_fdQUrlu-GvaWM8HsVgGY23kg6ZKZ_Uf

day 2 :stretch exercise -contact book menu
"""

contacts = {}

while True:
    print("\n1. Add contact")
    print("2. Search contact")
    print("3. Delete contact")
    print("4. Display all contacts")
    print("5. Exit")

    choice = input("Enter your choice (1-5): ").strip()

    if choice == "1":
        # Adding contact
        name = input("Enter name: ").strip()
        phone = input("Enter phone number: ").strip()
        email = input("Enter email address: ").strip()

        contacts[name] = {
            "phone": phone,
            "email": email
        }
        print(f"Contact '{name}' added successfully.")

    elif choice == "2":
        # Searching contact
        name = input("Enter name to search: ").strip()

        if name in contacts:
            details = contacts[name]
            print(f"Name: {name}")
            print(f"Phone: {details['phone']}")
            print(f"Email: {details['email']}")
        else:
            print(f"No contact found with the name '{name}'.")

    elif choice == "3":
        # Deleting contact
        name = input("Enter name to delete: ").strip()

        if name in contacts:
            del contacts[name]
            print(f"Contact '{name}' deleted successfully.")
        else:
            print(f"No contact found with the name '{name}'. Nothing to delete.")

    elif choice == "4":
        # Displaying all contacts
        if contacts:
            print("All contacts:")
            for name, details in contacts.items():
                print(f"- {name}: {details['phone']}, {details['email']}")
        else:
            print("No contacts saved yet.")

    elif choice == "5":
        # Exit
        print("Exiting contact book. Goodbye!")
        break

    else:
        print("Invalid choice. Please select a number between 1 and 5.")