# -*- coding: utf-8 -*-
"""exercise-05-pipeline-health-status.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rtp5xBcbFvqcuZT1ToW01DJO70RNyBc2

Day 01- excerise 5: Pipeline Health Status
"""

# Function to calculate failure rate and determine pipeline health
def pipeline_health(rows_loaded, rows_failed, runtime_minutes):
    # Calculate total number of rows
    total_rows = rows_loaded + rows_failed

    # Calculate failure rate as a percentage
    failure_rate = (rows_failed / total_rows) * 100


     # Determine pipeline status
    if failure_rate <= 2 and runtime_minutes <= 20:
        status = "Healthy"
    elif failure_rate > 5:
        status = "Critical"
    else:
        status = "Warning"

     # Display the results
    print(f"Failure Rate: {failure_rate:.2f}%")
    print(f"Pipeline Status: {status}")
    print()


# Test 1
pipeline_health(9800, 200, 18)

# Test 2
pipeline_health(9500, 500, 15)

# Test 3
pipeline_health(9900, 100, 30)