# -*- coding: utf-8 -*-
"""exercise-01-sales-summary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xv5BOJRnsaQyNWza_yNHIkOi6IZX3Pz-

Day 1 , Exercise 1: Sales Summary
"""

#Given Variables
Product_name= "Wireless Mouse "
unit_price=1500
quantity_sold= 12
discount_percentage=0.10

#Calculations
gross_sales= unit_price * quantity_sold
discount_amount= gross_sales * discount_percentage
final_sales= gross_sales - discount_amount


#Output using f string
print(f"Product: {Product_name}")
print(f"Gross Sales: NPR {gross_sales:.2f}")
print(f"Discount: NPR {discount_amount:.2f}")
print(f"Final sales: NPR {final_sales:.2f}")