# -*- coding: utf-8 -*-
"""exercise-02-data-quality-checker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Be8-AjFRCZmxXdDcthyJbDEzBmfNrF02

Day 1 , Exercise 2: Data Quality Checker
"""

# Given variables
total_rows= 2000
missing_rows=120
duplicate_rows= 30

#Calculations
problematic_rows= missing_rows + duplicate_rows
problem_percentage = (problematic_rows/total_rows)* 100


#Classification part
if problem_percentage <= 2:
  classification="Excellent"
elif problem_percentage <=5:
  classification="Acceptable"
else:
  classification= "Needs Cleaning"


#Output
print("Total rows: ", total_rows)
print("Problematic_rows: ", problematic_rows)
print(f"problem_percentage: {problem_percentage:.2f}%" )
print("Final Classification: ", classification)