# -*- coding: utf-8 -*-
"""exercise-03-file-validator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h1lopGxGHpQ4CHU9_ioWBwf3-td5xVTs

Day 1: Exercise 3
File Validator
"""

# File Validator
file_name = input("Enter the file name: ")
file_name = file_name.strip().lower()

# Check for valid extensions
if file_name.endswith(".csv") or file_name.endswith(".json") or file_name.endswith(".parquet"):
    print(f"'{file_name}' is a valid file type.")
else:
    print(f"'{file_name}' is NOT a valid file type. Accepted types: .csv, .json, .parquet")