# -*- coding: utf-8 -*-
"""exercise-04-custom-record-cleaner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nrCOO8sPhpGDrTZ-5sf0o5g2NfvGihEy

**Day 01 -exercise 4: custom record cleaner**
"""

# Given raw values
raw_name = "  sAgar THAPA "
raw_city = "kATHMANDU "
raw_age = "27"
raw_email = " SAGAR@MAIL.COM "

# Cleaning the values
name = raw_name.strip().title()
city = raw_city.strip().title()
age = int(raw_age.strip())
email = raw_email.strip().lower()

# Ternary expression for adult status
status = "Adult" if age >= 18 else "Minor"

# Displaying output
print(f"Name: {name}")
print(f"City: {city}")
print(f"Age: {age}")
print(f"Email: {email}")
print(f"Status: {status}")