# -*- coding: utf-8 -*-
"""stretch-access-decision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AcK6lMBTFg6w8fCeiYrmdKv3375jg85O

Day 1- strech exercise: Dataset Access Decision
"""

# Allowed roles that are permitted to request datasets
allowed_roles = ["analyst", "scientist", "engineer"]

# Datasets that are restricted regardless of role
restricted_datasets = ["salary_data", "personal_data"]


def check_access(user_role, is_active, requested_dataset):
    # Rule 1: user must be active
    if not is_active:
        print("Access denied because the user is inactive.")

    # Rule 2: role must be in the allowed list
    elif user_role not in allowed_roles:
        print("Access denied because the role is not allowed.")

    # Rule 3: dataset must not be restricted
    elif requested_dataset in restricted_datasets:
        print("Access denied because the dataset is restricted.")

    # If all three conditions pass, grant access
    else:
        print("Access granted.")


# Scenario 1: Active user, allowed role, non-restricted dataset -> should be granted
print("Scenario 1:")
user_role = "analyst"
is_active = True
requested_dataset = "sales_data"
check_access(user_role, is_active, requested_dataset)
print()

# Scenario 2: Inactive user -> should be denied (inactive)
print("Scenario 2:")
user_role = "scientist"
is_active = False
requested_dataset = "sales_data"
check_access(user_role, is_active, requested_dataset)
print()

# Scenario 3: Role not in allowed list -> should be denied (role not allowed)
print("Scenario 3:")
user_role = "intern"
is_active = True
requested_dataset = "sales_data"
check_access(user_role, is_active, requested_dataset)
print()

# Scenario 4: Active user, allowed role, but dataset is restricted -> should be denied (dataset restricted)
print("Scenario 4:")
user_role = "engineer"
is_active = True
requested_dataset = "salary_data"
check_access(user_role, is_active, requested_dataset)